packages:
  - .

allowBuilds:
  '@deepseek-ai/dsh-subprocess-local': true
  '@google/genai': false
  esbuild: true
  koffi: true
  node-pty: true
  protobufjs: false
  sharp: true

overrides:
  '@deepseek-ai/cordis': 4.0.2
