/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { CreateNoteInput, DeleteNotebookInput, ImageData, ImageDataInput, MutationResult, Note, Notebook, NotebookIdInput, NotebookOverview, NoteIdInput, NoteImageInput, NoteLifecycleInput, NoteRevisionInput, NoteRevisionResult, NoteSearchInput, NoteSearchResult, RenameNotebookInput, RestoreRevisionInput, UpdateNoteInput } from 'dsh-notebook/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6e6f7465626f6f6b {
    addImage: (input: NoteImageInput, signal?: AbortSignal) => Promise<RemoteResult<Note>>
    archive: (input: NoteLifecycleInput, signal?: AbortSignal) => Promise<RemoteResult<Note>>
    create: (input: CreateNoteInput, signal?: AbortSignal) => Promise<RemoteResult<Note>>
    createNotebook: (input: { name: string; }, signal?: AbortSignal) => Promise<RemoteResult<Notebook>>
    deleteNote: (input: NoteLifecycleInput, signal?: AbortSignal) => Promise<RemoteResult<MutationResult>>
    deleteNotebook: (input: DeleteNotebookInput, signal?: AbortSignal) => Promise<RemoteResult<MutationResult>>
    imageData: (input: ImageDataInput, signal?: AbortSignal) => Promise<RemoteResult<ImageData>>
    notebook: (input: NotebookIdInput, signal?: AbortSignal) => Promise<RemoteResult<Notebook>>
    overview: (_input: Record<string, never>, signal?: AbortSignal) => Promise<RemoteResult<NotebookOverview>>
    read: (input: NoteIdInput, signal?: AbortSignal) => Promise<RemoteResult<Note>>
    renameNotebook: (input: RenameNotebookInput, signal?: AbortSignal) => Promise<RemoteResult<Notebook>>
    restore: (input: NoteLifecycleInput, signal?: AbortSignal) => Promise<RemoteResult<Note>>
    restoreRevision: (input: RestoreRevisionInput, signal?: AbortSignal) => Promise<RemoteResult<Note>>
    revisions: (input: NoteRevisionInput, signal?: AbortSignal) => Promise<RemoteResult<NoteRevisionResult>>
    search: (input: NoteSearchInput, signal?: AbortSignal) => Promise<RemoteResult<NoteSearchResult>>
    update: (input: UpdateNoteInput, signal?: AbortSignal) => Promise<RemoteResult<Note>>
  }
  interface TypertRemoteMap {
    'notebook/addImage': (input: NoteImageInput, signal?: AbortSignal) => Promise<RemoteResult<Note>>
    'notebook/archive': (input: NoteLifecycleInput, signal?: AbortSignal) => Promise<RemoteResult<Note>>
    'notebook/create': (input: CreateNoteInput, signal?: AbortSignal) => Promise<RemoteResult<Note>>
    'notebook/createNotebook': (input: { name: string; }, signal?: AbortSignal) => Promise<RemoteResult<Notebook>>
    'notebook/deleteNote': (input: NoteLifecycleInput, signal?: AbortSignal) => Promise<RemoteResult<MutationResult>>
    'notebook/deleteNotebook': (input: DeleteNotebookInput, signal?: AbortSignal) => Promise<RemoteResult<MutationResult>>
    'notebook/imageData': (input: ImageDataInput, signal?: AbortSignal) => Promise<RemoteResult<ImageData>>
    'notebook/notebook': (input: NotebookIdInput, signal?: AbortSignal) => Promise<RemoteResult<Notebook>>
    'notebook/overview': (_input: Record<string, never>, signal?: AbortSignal) => Promise<RemoteResult<NotebookOverview>>
    'notebook/read': (input: NoteIdInput, signal?: AbortSignal) => Promise<RemoteResult<Note>>
    'notebook/renameNotebook': (input: RenameNotebookInput, signal?: AbortSignal) => Promise<RemoteResult<Notebook>>
    'notebook/restore': (input: NoteLifecycleInput, signal?: AbortSignal) => Promise<RemoteResult<Note>>
    'notebook/restoreRevision': (input: RestoreRevisionInput, signal?: AbortSignal) => Promise<RemoteResult<Note>>
    'notebook/revisions': (input: NoteRevisionInput, signal?: AbortSignal) => Promise<RemoteResult<NoteRevisionResult>>
    'notebook/search': (input: NoteSearchInput, signal?: AbortSignal) => Promise<RemoteResult<NoteSearchResult>>
    'notebook/update': (input: UpdateNoteInput, signal?: AbortSignal) => Promise<RemoteResult<Note>>
  }
  interface TypertRemoteNamespaceMap {
    'notebook': TypertRemoteNamespace$6e6f7465626f6f6b
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
