/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

let dsh_notebook_notebook_addImage_parameter_0$schema$value
const dsh_notebook_notebook_addImage_parameter_0$schema = () => (dsh_notebook_notebook_addImage_parameter_0$schema$value ??= z.object({
  'noteId': z.intersection(z.string(), z.unknown()).readonly(),
  'expectedRevision': z.number().readonly(),
  'image': z.object({
  'name': z.string().readonly(),
  'mediaType': z.union([z.literal("image/png"), z.literal("image/jpeg"), z.literal("image/webp"), z.literal("image/gif")]).readonly(),
  'data': z.string().readonly(),
}).readonly(),
}))
let dsh_notebook_notebook_addImage_result$schema$value
const dsh_notebook_notebook_addImage_result$schema = () => (dsh_notebook_notebook_addImage_result$schema$value ??= z.object({
  'body': z.string().readonly(),
  'images': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'noteId': z.intersection(z.string(), z.unknown()).readonly(),
  'name': z.string().readonly(),
  'mediaType': z.union([z.literal("image/png"), z.literal("image/jpeg"), z.literal("image/webp"), z.literal("image/gif")]).readonly(),
  'bytes': z.number().readonly(),
  'width': z.number().readonly(),
  'height': z.number().readonly(),
  'digest': z.string().readonly(),
  'position': z.number().readonly(),
  'createdAt': z.string().readonly(),
})).readonly(),
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'notebookId': z.intersection(z.string(), z.unknown()).readonly(),
  'notebookName': z.string().readonly(),
  'title': z.string().readonly(),
  'excerpt': z.string().readonly(),
  'tags': z.array(z.string()).readonly(),
  'imageCount': z.number().readonly(),
  'revision': z.number().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'archivedAt': z.union([z.literal(null), z.string()]).readonly(),
}))
let dsh_notebook_notebook_archive_parameter_0$schema$value
const dsh_notebook_notebook_archive_parameter_0$schema = () => (dsh_notebook_notebook_archive_parameter_0$schema$value ??= z.object({
  'expectedRevision': z.number().readonly(),
  'id': z.intersection(z.string(), z.unknown()).readonly(),
}))
let dsh_notebook_notebook_archive_result$schema$value
const dsh_notebook_notebook_archive_result$schema = () => (dsh_notebook_notebook_archive_result$schema$value ??= z.object({
  'body': z.string().readonly(),
  'images': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'noteId': z.intersection(z.string(), z.unknown()).readonly(),
  'name': z.string().readonly(),
  'mediaType': z.union([z.literal("image/png"), z.literal("image/jpeg"), z.literal("image/webp"), z.literal("image/gif")]).readonly(),
  'bytes': z.number().readonly(),
  'width': z.number().readonly(),
  'height': z.number().readonly(),
  'digest': z.string().readonly(),
  'position': z.number().readonly(),
  'createdAt': z.string().readonly(),
})).readonly(),
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'notebookId': z.intersection(z.string(), z.unknown()).readonly(),
  'notebookName': z.string().readonly(),
  'title': z.string().readonly(),
  'excerpt': z.string().readonly(),
  'tags': z.array(z.string()).readonly(),
  'imageCount': z.number().readonly(),
  'revision': z.number().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'archivedAt': z.union([z.literal(null), z.string()]).readonly(),
}))
let dsh_notebook_notebook_create_parameter_0$schema$value
const dsh_notebook_notebook_create_parameter_0$schema = () => (dsh_notebook_notebook_create_parameter_0$schema$value ??= z.object({
  'notebookId': z.union([z.undefined(), z.intersection(z.string(), z.unknown())]).readonly().optional(),
  'notebookName': z.union([z.undefined(), z.string()]).readonly().optional(),
  'title': z.string().readonly(),
  'body': z.string().readonly(),
  'tags': z.union([z.undefined(), z.array(z.string())]).readonly().optional(),
  'images': z.union([z.undefined(), z.array(z.object({
  'name': z.string().readonly(),
  'mediaType': z.union([z.literal("image/png"), z.literal("image/jpeg"), z.literal("image/webp"), z.literal("image/gif")]).readonly(),
  'data': z.string().readonly(),
}))]).readonly().optional(),
}))
let dsh_notebook_notebook_create_result$schema$value
const dsh_notebook_notebook_create_result$schema = () => (dsh_notebook_notebook_create_result$schema$value ??= z.object({
  'body': z.string().readonly(),
  'images': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'noteId': z.intersection(z.string(), z.unknown()).readonly(),
  'name': z.string().readonly(),
  'mediaType': z.union([z.literal("image/png"), z.literal("image/jpeg"), z.literal("image/webp"), z.literal("image/gif")]).readonly(),
  'bytes': z.number().readonly(),
  'width': z.number().readonly(),
  'height': z.number().readonly(),
  'digest': z.string().readonly(),
  'position': z.number().readonly(),
  'createdAt': z.string().readonly(),
})).readonly(),
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'notebookId': z.intersection(z.string(), z.unknown()).readonly(),
  'notebookName': z.string().readonly(),
  'title': z.string().readonly(),
  'excerpt': z.string().readonly(),
  'tags': z.array(z.string()).readonly(),
  'imageCount': z.number().readonly(),
  'revision': z.number().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'archivedAt': z.union([z.literal(null), z.string()]).readonly(),
}))
let dsh_notebook_notebook_createNotebook_parameter_0$schema$value
const dsh_notebook_notebook_createNotebook_parameter_0$schema = () => (dsh_notebook_notebook_createNotebook_parameter_0$schema$value ??= z.object({
  'name': z.string(),
}))
let dsh_notebook_notebook_createNotebook_result$schema$value
const dsh_notebook_notebook_createNotebook_result$schema = () => (dsh_notebook_notebook_createNotebook_result$schema$value ??= z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'name': z.string().readonly(),
  'revision': z.number().readonly(),
  'noteCount': z.number().readonly(),
  'archivedNoteCount': z.number().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
}))
let dsh_notebook_notebook_deleteNote_parameter_0$schema$value
const dsh_notebook_notebook_deleteNote_parameter_0$schema = () => (dsh_notebook_notebook_deleteNote_parameter_0$schema$value ??= z.object({
  'expectedRevision': z.number().readonly(),
  'id': z.intersection(z.string(), z.unknown()).readonly(),
}))
let dsh_notebook_notebook_deleteNote_result$schema$value
const dsh_notebook_notebook_deleteNote_result$schema = () => (dsh_notebook_notebook_deleteNote_result$schema$value ??= z.object({
  'ok': z.literal(true).readonly(),
}))
let dsh_notebook_notebook_deleteNotebook_parameter_0$schema$value
const dsh_notebook_notebook_deleteNotebook_parameter_0$schema = () => (dsh_notebook_notebook_deleteNotebook_parameter_0$schema$value ??= z.object({
  'expectedRevision': z.number().readonly(),
  'id': z.intersection(z.string(), z.unknown()).readonly(),
}))
let dsh_notebook_notebook_deleteNotebook_result$schema$value
const dsh_notebook_notebook_deleteNotebook_result$schema = () => (dsh_notebook_notebook_deleteNotebook_result$schema$value ??= z.object({
  'ok': z.literal(true).readonly(),
}))
let dsh_notebook_notebook_imageData_parameter_0$schema$value
const dsh_notebook_notebook_imageData_parameter_0$schema = () => (dsh_notebook_notebook_imageData_parameter_0$schema$value ??= z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
}))
let dsh_notebook_notebook_imageData_result$schema$value
const dsh_notebook_notebook_imageData_result$schema = () => (dsh_notebook_notebook_imageData_result$schema$value ??= z.object({
  'image': z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'noteId': z.intersection(z.string(), z.unknown()).readonly(),
  'name': z.string().readonly(),
  'mediaType': z.union([z.literal("image/png"), z.literal("image/jpeg"), z.literal("image/webp"), z.literal("image/gif")]).readonly(),
  'bytes': z.number().readonly(),
  'width': z.number().readonly(),
  'height': z.number().readonly(),
  'digest': z.string().readonly(),
  'position': z.number().readonly(),
  'createdAt': z.string().readonly(),
}).readonly(),
  'data': z.string().readonly(),
}))
let dsh_notebook_notebook_notebook_parameter_0$schema$value
const dsh_notebook_notebook_notebook_parameter_0$schema = () => (dsh_notebook_notebook_notebook_parameter_0$schema$value ??= z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
}))
let dsh_notebook_notebook_notebook_result$schema$value
const dsh_notebook_notebook_notebook_result$schema = () => (dsh_notebook_notebook_notebook_result$schema$value ??= z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'name': z.string().readonly(),
  'revision': z.number().readonly(),
  'noteCount': z.number().readonly(),
  'archivedNoteCount': z.number().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
}))
let dsh_notebook_notebook_overview_parameter_0$schema$value
const dsh_notebook_notebook_overview_parameter_0$schema = () => (dsh_notebook_notebook_overview_parameter_0$schema$value ??= z.record(z.string(), z.never()))
let dsh_notebook_notebook_overview_result$schema$value
const dsh_notebook_notebook_overview_result$schema = () => (dsh_notebook_notebook_overview_result$schema$value ??= z.object({
  'notebooks': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'name': z.string().readonly(),
  'revision': z.number().readonly(),
  'noteCount': z.number().readonly(),
  'archivedNoteCount': z.number().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
})).readonly(),
  'tags': z.array(z.string()).readonly(),
  'activeNotes': z.number().readonly(),
  'archivedNotes': z.number().readonly(),
}))
let dsh_notebook_notebook_read_parameter_0$schema$value
const dsh_notebook_notebook_read_parameter_0$schema = () => (dsh_notebook_notebook_read_parameter_0$schema$value ??= z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
}))
let dsh_notebook_notebook_read_result$schema$value
const dsh_notebook_notebook_read_result$schema = () => (dsh_notebook_notebook_read_result$schema$value ??= z.object({
  'body': z.string().readonly(),
  'images': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'noteId': z.intersection(z.string(), z.unknown()).readonly(),
  'name': z.string().readonly(),
  'mediaType': z.union([z.literal("image/png"), z.literal("image/jpeg"), z.literal("image/webp"), z.literal("image/gif")]).readonly(),
  'bytes': z.number().readonly(),
  'width': z.number().readonly(),
  'height': z.number().readonly(),
  'digest': z.string().readonly(),
  'position': z.number().readonly(),
  'createdAt': z.string().readonly(),
})).readonly(),
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'notebookId': z.intersection(z.string(), z.unknown()).readonly(),
  'notebookName': z.string().readonly(),
  'title': z.string().readonly(),
  'excerpt': z.string().readonly(),
  'tags': z.array(z.string()).readonly(),
  'imageCount': z.number().readonly(),
  'revision': z.number().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'archivedAt': z.union([z.literal(null), z.string()]).readonly(),
}))
let dsh_notebook_notebook_renameNotebook_parameter_0$schema$value
const dsh_notebook_notebook_renameNotebook_parameter_0$schema = () => (dsh_notebook_notebook_renameNotebook_parameter_0$schema$value ??= z.object({
  'expectedRevision': z.number().readonly(),
  'name': z.string().readonly(),
  'id': z.intersection(z.string(), z.unknown()).readonly(),
}))
let dsh_notebook_notebook_renameNotebook_result$schema$value
const dsh_notebook_notebook_renameNotebook_result$schema = () => (dsh_notebook_notebook_renameNotebook_result$schema$value ??= z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'name': z.string().readonly(),
  'revision': z.number().readonly(),
  'noteCount': z.number().readonly(),
  'archivedNoteCount': z.number().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
}))
let dsh_notebook_notebook_restore_parameter_0$schema$value
const dsh_notebook_notebook_restore_parameter_0$schema = () => (dsh_notebook_notebook_restore_parameter_0$schema$value ??= z.object({
  'expectedRevision': z.number().readonly(),
  'id': z.intersection(z.string(), z.unknown()).readonly(),
}))
let dsh_notebook_notebook_restore_result$schema$value
const dsh_notebook_notebook_restore_result$schema = () => (dsh_notebook_notebook_restore_result$schema$value ??= z.object({
  'body': z.string().readonly(),
  'images': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'noteId': z.intersection(z.string(), z.unknown()).readonly(),
  'name': z.string().readonly(),
  'mediaType': z.union([z.literal("image/png"), z.literal("image/jpeg"), z.literal("image/webp"), z.literal("image/gif")]).readonly(),
  'bytes': z.number().readonly(),
  'width': z.number().readonly(),
  'height': z.number().readonly(),
  'digest': z.string().readonly(),
  'position': z.number().readonly(),
  'createdAt': z.string().readonly(),
})).readonly(),
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'notebookId': z.intersection(z.string(), z.unknown()).readonly(),
  'notebookName': z.string().readonly(),
  'title': z.string().readonly(),
  'excerpt': z.string().readonly(),
  'tags': z.array(z.string()).readonly(),
  'imageCount': z.number().readonly(),
  'revision': z.number().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'archivedAt': z.union([z.literal(null), z.string()]).readonly(),
}))
let dsh_notebook_notebook_restoreRevision_parameter_0$schema$value
const dsh_notebook_notebook_restoreRevision_parameter_0$schema = () => (dsh_notebook_notebook_restoreRevision_parameter_0$schema$value ??= z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'revision': z.number().readonly(),
  'expectedRevision': z.number().readonly(),
}))
let dsh_notebook_notebook_restoreRevision_result$schema$value
const dsh_notebook_notebook_restoreRevision_result$schema = () => (dsh_notebook_notebook_restoreRevision_result$schema$value ??= z.object({
  'body': z.string().readonly(),
  'images': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'noteId': z.intersection(z.string(), z.unknown()).readonly(),
  'name': z.string().readonly(),
  'mediaType': z.union([z.literal("image/png"), z.literal("image/jpeg"), z.literal("image/webp"), z.literal("image/gif")]).readonly(),
  'bytes': z.number().readonly(),
  'width': z.number().readonly(),
  'height': z.number().readonly(),
  'digest': z.string().readonly(),
  'position': z.number().readonly(),
  'createdAt': z.string().readonly(),
})).readonly(),
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'notebookId': z.intersection(z.string(), z.unknown()).readonly(),
  'notebookName': z.string().readonly(),
  'title': z.string().readonly(),
  'excerpt': z.string().readonly(),
  'tags': z.array(z.string()).readonly(),
  'imageCount': z.number().readonly(),
  'revision': z.number().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'archivedAt': z.union([z.literal(null), z.string()]).readonly(),
}))
let dsh_notebook_notebook_revisions_parameter_0$schema$value
const dsh_notebook_notebook_revisions_parameter_0$schema = () => (dsh_notebook_notebook_revisions_parameter_0$schema$value ??= z.object({
  'limit': z.union([z.undefined(), z.number()]).readonly().optional(),
  'offset': z.union([z.undefined(), z.number()]).readonly().optional(),
  'id': z.intersection(z.string(), z.unknown()).readonly(),
}))
let dsh_notebook_notebook_revisions_result$schema$value
const dsh_notebook_notebook_revisions_result$schema = () => (dsh_notebook_notebook_revisions_result$schema$value ??= z.object({
  'revisions': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'noteId': z.intersection(z.string(), z.unknown()).readonly(),
  'revision': z.number().readonly(),
  'notebookId': z.intersection(z.string(), z.unknown()).readonly(),
  'notebookName': z.string().readonly(),
  'title': z.string().readonly(),
  'body': z.string().readonly(),
  'tags': z.array(z.string()).readonly(),
  'images': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'noteId': z.intersection(z.string(), z.unknown()).readonly(),
  'name': z.string().readonly(),
  'mediaType': z.union([z.literal("image/png"), z.literal("image/jpeg"), z.literal("image/webp"), z.literal("image/gif")]).readonly(),
  'bytes': z.number().readonly(),
  'width': z.number().readonly(),
  'height': z.number().readonly(),
  'digest': z.string().readonly(),
  'position': z.number().readonly(),
  'createdAt': z.string().readonly(),
})).readonly(),
  'archivedAt': z.union([z.literal(null), z.string()]).readonly(),
  'createdAt': z.string().readonly(),
})).readonly(),
  'total': z.number().readonly(),
  'hasMore': z.boolean().readonly(),
}))
let dsh_notebook_notebook_search_parameter_0$schema$value
const dsh_notebook_notebook_search_parameter_0$schema = () => (dsh_notebook_notebook_search_parameter_0$schema$value ??= z.object({
  'query': z.union([z.undefined(), z.string()]).readonly().optional(),
  'notebookId': z.union([z.undefined(), z.intersection(z.string(), z.unknown())]).readonly().optional(),
  'tags': z.union([z.undefined(), z.array(z.string())]).readonly().optional(),
  'archived': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
  'limit': z.union([z.undefined(), z.number()]).readonly().optional(),
  'offset': z.union([z.undefined(), z.number()]).readonly().optional(),
}))
let dsh_notebook_notebook_search_result$schema$value
const dsh_notebook_notebook_search_result$schema = () => (dsh_notebook_notebook_search_result$schema$value ??= z.object({
  'notes': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'notebookId': z.intersection(z.string(), z.unknown()).readonly(),
  'notebookName': z.string().readonly(),
  'title': z.string().readonly(),
  'excerpt': z.string().readonly(),
  'tags': z.array(z.string()).readonly(),
  'imageCount': z.number().readonly(),
  'revision': z.number().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'archivedAt': z.union([z.literal(null), z.string()]).readonly(),
})).readonly(),
  'total': z.number().readonly(),
  'hasMore': z.boolean().readonly(),
}))
let dsh_notebook_notebook_update_parameter_0$schema$value
const dsh_notebook_notebook_update_parameter_0$schema = () => (dsh_notebook_notebook_update_parameter_0$schema$value ??= z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'expectedRevision': z.number().readonly(),
  'mode': z.union([z.literal("append"), z.literal("replace")]).readonly(),
  'title': z.union([z.undefined(), z.string()]).readonly().optional(),
  'body': z.union([z.undefined(), z.string()]).readonly().optional(),
  'notebookId': z.union([z.undefined(), z.intersection(z.string(), z.unknown())]).readonly().optional(),
  'notebookName': z.union([z.undefined(), z.string()]).readonly().optional(),
  'tags': z.union([z.undefined(), z.array(z.string())]).readonly().optional(),
  'images': z.union([z.undefined(), z.array(z.object({
  'name': z.string().readonly(),
  'mediaType': z.union([z.literal("image/png"), z.literal("image/jpeg"), z.literal("image/webp"), z.literal("image/gif")]).readonly(),
  'data': z.string().readonly(),
}))]).readonly().optional(),
  'removeImageIds': z.union([z.undefined(), z.array(z.intersection(z.string(), z.unknown()))]).readonly().optional(),
}))
let dsh_notebook_notebook_update_result$schema$value
const dsh_notebook_notebook_update_result$schema = () => (dsh_notebook_notebook_update_result$schema$value ??= z.object({
  'body': z.string().readonly(),
  'images': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'noteId': z.intersection(z.string(), z.unknown()).readonly(),
  'name': z.string().readonly(),
  'mediaType': z.union([z.literal("image/png"), z.literal("image/jpeg"), z.literal("image/webp"), z.literal("image/gif")]).readonly(),
  'bytes': z.number().readonly(),
  'width': z.number().readonly(),
  'height': z.number().readonly(),
  'digest': z.string().readonly(),
  'position': z.number().readonly(),
  'createdAt': z.string().readonly(),
})).readonly(),
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'notebookId': z.intersection(z.string(), z.unknown()).readonly(),
  'notebookName': z.string().readonly(),
  'title': z.string().readonly(),
  'excerpt': z.string().readonly(),
  'tags': z.array(z.string()).readonly(),
  'imageCount': z.number().readonly(),
  'revision': z.number().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'archivedAt': z.union([z.literal(null), z.string()]).readonly(),
}))

export const TYPERT = {
  package: 'dsh-notebook',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-notebook#notebook/addImage',
      service: 'notebook',
      namespace: 'notebook',
      method: 'addImage',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'input',
          wire: 'input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-notebook/types#NoteImageInput',
            create: dsh_notebook_notebook_addImage_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-notebook/types#Note',
        create: dsh_notebook_notebook_addImage_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-notebook/src/index.ts","line":142,"column":3},
    },
    {
      id: 'dsh-notebook#notebook/archive',
      service: 'notebook',
      namespace: 'notebook',
      method: 'archive',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'input',
          wire: 'input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-notebook/types#NoteLifecycleInput',
            create: dsh_notebook_notebook_archive_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-notebook/types#Note',
        create: dsh_notebook_notebook_archive_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-notebook/src/index.ts","line":93,"column":3},
    },
    {
      id: 'dsh-notebook#notebook/create',
      service: 'notebook',
      namespace: 'notebook',
      method: 'create',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'input',
          wire: 'input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-notebook/types#CreateNoteInput',
            create: dsh_notebook_notebook_create_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-notebook/types#Note',
        create: dsh_notebook_notebook_create_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-notebook/src/index.ts","line":79,"column":3},
    },
    {
      id: 'dsh-notebook#notebook/createNotebook',
      service: 'notebook',
      namespace: 'notebook',
      method: 'createNotebook',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'input',
          wire: 'input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-notebook#notebook/createNotebook:input',
            create: dsh_notebook_notebook_createNotebook_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-notebook/types#Notebook',
        create: dsh_notebook_notebook_createNotebook_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-notebook/src/index.ts","line":156,"column":3},
    },
    {
      id: 'dsh-notebook#notebook/deleteNote',
      service: 'notebook',
      namespace: 'notebook',
      method: 'deleteNote',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'input',
          wire: 'input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-notebook/types#NoteLifecycleInput',
            create: dsh_notebook_notebook_deleteNote_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-notebook/types#MutationResult',
        create: dsh_notebook_notebook_deleteNote_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-notebook/src/index.ts","line":107,"column":3},
    },
    {
      id: 'dsh-notebook#notebook/deleteNotebook',
      service: 'notebook',
      namespace: 'notebook',
      method: 'deleteNotebook',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'input',
          wire: 'input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-notebook/types#DeleteNotebookInput',
            create: dsh_notebook_notebook_deleteNotebook_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-notebook/types#MutationResult',
        create: dsh_notebook_notebook_deleteNotebook_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-notebook/src/index.ts","line":121,"column":3},
    },
    {
      id: 'dsh-notebook#notebook/imageData',
      service: 'notebook',
      namespace: 'notebook',
      method: 'imageData',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'input',
          wire: 'input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-notebook/types#ImageDataInput',
            create: dsh_notebook_notebook_imageData_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-notebook/types#ImageData',
        create: dsh_notebook_notebook_imageData_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-notebook/src/index.ts","line":149,"column":3},
    },
    {
      id: 'dsh-notebook#notebook/notebook',
      service: 'notebook',
      namespace: 'notebook',
      method: 'notebook',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'input',
          wire: 'input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-notebook/types#NotebookIdInput',
            create: dsh_notebook_notebook_notebook_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-notebook/types#Notebook',
        create: dsh_notebook_notebook_notebook_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-notebook/src/index.ts","line":163,"column":3},
    },
    {
      id: 'dsh-notebook#notebook/overview',
      service: 'notebook',
      namespace: 'notebook',
      method: 'overview',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: '_input',
          wire: '_input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-notebook#notebook/overview:_input',
            create: dsh_notebook_notebook_overview_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-notebook/types#NotebookOverview',
        create: dsh_notebook_notebook_overview_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-notebook/src/index.ts","line":58,"column":3},
    },
    {
      id: 'dsh-notebook#notebook/read',
      service: 'notebook',
      namespace: 'notebook',
      method: 'read',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'input',
          wire: 'input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-notebook/types#NoteIdInput',
            create: dsh_notebook_notebook_read_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-notebook/types#Note',
        create: dsh_notebook_notebook_read_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-notebook/src/index.ts","line":72,"column":3},
    },
    {
      id: 'dsh-notebook#notebook/renameNotebook',
      service: 'notebook',
      namespace: 'notebook',
      method: 'renameNotebook',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'input',
          wire: 'input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-notebook/types#RenameNotebookInput',
            create: dsh_notebook_notebook_renameNotebook_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-notebook/types#Notebook',
        create: dsh_notebook_notebook_renameNotebook_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-notebook/src/index.ts","line":114,"column":3},
    },
    {
      id: 'dsh-notebook#notebook/restore',
      service: 'notebook',
      namespace: 'notebook',
      method: 'restore',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'input',
          wire: 'input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-notebook/types#NoteLifecycleInput',
            create: dsh_notebook_notebook_restore_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-notebook/types#Note',
        create: dsh_notebook_notebook_restore_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-notebook/src/index.ts","line":100,"column":3},
    },
    {
      id: 'dsh-notebook#notebook/restoreRevision',
      service: 'notebook',
      namespace: 'notebook',
      method: 'restoreRevision',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'input',
          wire: 'input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-notebook/types#RestoreRevisionInput',
            create: dsh_notebook_notebook_restoreRevision_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-notebook/types#Note',
        create: dsh_notebook_notebook_restoreRevision_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-notebook/src/index.ts","line":135,"column":3},
    },
    {
      id: 'dsh-notebook#notebook/revisions',
      service: 'notebook',
      namespace: 'notebook',
      method: 'revisions',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'input',
          wire: 'input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-notebook/types#NoteRevisionInput',
            create: dsh_notebook_notebook_revisions_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-notebook/types#NoteRevisionResult',
        create: dsh_notebook_notebook_revisions_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-notebook/src/index.ts","line":128,"column":3},
    },
    {
      id: 'dsh-notebook#notebook/search',
      service: 'notebook',
      namespace: 'notebook',
      method: 'search',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'input',
          wire: 'input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-notebook/types#NoteSearchInput',
            create: dsh_notebook_notebook_search_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-notebook/types#NoteSearchResult',
        create: dsh_notebook_notebook_search_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-notebook/src/index.ts","line":65,"column":3},
    },
    {
      id: 'dsh-notebook#notebook/update',
      service: 'notebook',
      namespace: 'notebook',
      method: 'update',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'input',
          wire: 'input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-notebook/types#UpdateNoteInput',
            create: dsh_notebook_notebook_update_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-notebook/types#Note',
        create: dsh_notebook_notebook_update_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-notebook/src/index.ts","line":86,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "description": "Persistent notebook service and browser Remote implementation.",
        "summary": "Persistent notebook service and browser Remote implementation.",
        "tags": [],
        "jsDoc": "/** Persistent notebook service and browser Remote implementation. */",
        "key": "notebook",
        "exportName": "NotebookService",
        "members": [
          {
            "kind": "property",
            "name": "store",
            "signature": "readonly store: NotebookStore"
          },
          {
            "kind": "method",
            "name": "overview",
            "signature": "@Remote overview(_input: Record<string, never>, signal: AbortSignal): Promise<NotebookOverview>",
            "summary": "Return notebook, tag and lifecycle counts.",
            "jsDoc": "/** Return notebook, tag and lifecycle counts. @param _input Empty request. @param signal Cancellation. @returns Current overview. */"
          },
          {
            "kind": "method",
            "name": "search",
            "signature": "@Remote search(input: NoteSearchInput, signal: AbortSignal): Promise<NoteSearchResult>",
            "summary": "Search notes with bounded pagination.",
            "jsDoc": "/** Search notes with bounded pagination. @param input Filters and query. @param signal Cancellation. @returns Matching summaries. */"
          },
          {
            "kind": "method",
            "name": "read",
            "signature": "@Remote read(input: NoteIdInput, signal: AbortSignal): Promise<Note>",
            "summary": "Read one complete note.",
            "jsDoc": "/** Read one complete note. @param input Note identity. @param signal Cancellation. @returns Current note. */"
          },
          {
            "kind": "method",
            "name": "create",
            "signature": "@Remote create(input: CreateNoteInput, signal: AbortSignal): Promise<Note>",
            "summary": "Create one note and optional notebook.",
            "jsDoc": "/** Create one note and optional notebook. @param input Note fields. @param signal Cancellation. @returns Created note. */"
          },
          {
            "kind": "method",
            "name": "update",
            "signature": "@Remote update(input: UpdateNoteInput, signal: AbortSignal): Promise<Note>",
            "summary": "Update one note with optimistic concurrency.",
            "jsDoc": "/** Update one note with optimistic concurrency. @param input Replacement or append request. @param signal Cancellation. @returns Updated note. */"
          },
          {
            "kind": "method",
            "name": "archive",
            "signature": "@Remote archive(input: NoteLifecycleInput, signal: AbortSignal): Promise<Note>",
            "summary": "Archive one active note.",
            "jsDoc": "/** Archive one active note. @param input Identity and revision. @param signal Cancellation. @returns Archived note. */"
          },
          {
            "kind": "method",
            "name": "restore",
            "signature": "@Remote restore(input: NoteLifecycleInput, signal: AbortSignal): Promise<Note>",
            "summary": "Restore one archived note.",
            "jsDoc": "/** Restore one archived note. @param input Identity and revision. @param signal Cancellation. @returns Active note. */"
          },
          {
            "kind": "method",
            "name": "deleteNote",
            "signature": "@Remote deleteNote(input: NoteLifecycleInput, signal: AbortSignal): Promise<MutationResult>",
            "summary": "Permanently delete one archived note.",
            "jsDoc": "/** Permanently delete one archived note. @param input Identity and revision. @param signal Cancellation. @returns Success. */"
          },
          {
            "kind": "method",
            "name": "renameNotebook",
            "signature": "@Remote renameNotebook(input: RenameNotebookInput, signal: AbortSignal): Promise<Notebook>",
            "summary": "Rename one notebook.",
            "jsDoc": "/** Rename one notebook. @param input Identity, revision and name. @param signal Cancellation. @returns Updated notebook. */"
          },
          {
            "kind": "method",
            "name": "deleteNotebook",
            "signature": "@Remote deleteNotebook(input: DeleteNotebookInput, signal: AbortSignal): Promise<MutationResult>",
            "summary": "Delete one empty notebook.",
            "jsDoc": "/** Delete one empty notebook. @param input Identity and revision. @param signal Cancellation. @returns Success. */"
          },
          {
            "kind": "method",
            "name": "revisions",
            "signature": "@Remote revisions(input: NoteRevisionInput, signal: AbortSignal): Promise<NoteRevisionResult>",
            "summary": "List immutable snapshots.",
            "jsDoc": "/** List immutable snapshots. @param input Note and pagination. @param signal Cancellation. @returns Revision page. */"
          },
          {
            "kind": "method",
            "name": "restoreRevision",
            "signature": "@Remote restoreRevision(input: RestoreRevisionInput, signal: AbortSignal): Promise<Note>",
            "summary": "Restore one snapshot as a new version.",
            "jsDoc": "/** Restore one snapshot as a new version. @param input Note and revision identities. @param signal Cancellation. @returns Restored note. */"
          },
          {
            "kind": "method",
            "name": "addImage",
            "signature": "@Remote addImage(input: NoteImageInput, signal: AbortSignal): Promise<Note>",
            "summary": "Add a panel-uploaded image.",
            "jsDoc": "/** Add a panel-uploaded image. @param input Note revision and encoded image. @param signal Cancellation. @returns Updated note. */"
          },
          {
            "kind": "method",
            "name": "imageData",
            "signature": "@Remote imageData(input: ImageDataInput, signal: AbortSignal): Promise<ImageData>",
            "summary": "Read verified image bytes for panel display.",
            "jsDoc": "/** Read verified image bytes for panel display. @param input Image identity. @param signal Cancellation. @returns Image metadata and base64. */"
          },
          {
            "kind": "method",
            "name": "createNotebook",
            "signature": "@Remote createNotebook(input: { name: string }, signal: AbortSignal): Promise<Notebook>",
            "summary": "Create an empty notebook for panel navigation.",
            "jsDoc": "/** Create an empty notebook for panel navigation. @param input Requested name. @param signal Cancellation. @returns Created notebook. */"
          },
          {
            "kind": "method",
            "name": "notebook",
            "signature": "@Remote notebook(input: NotebookIdInput, signal: AbortSignal): Promise<Notebook>",
            "summary": "Check that a notebook exists.",
            "jsDoc": "/** Check that a notebook exists. @param input Notebook identity. @param signal Cancellation. @returns Current overview entry. */"
          }
        ],
        "types": [
          {
            "name": "CreateNoteInput",
            "declaration": "export interface CreateNoteInput {\n    readonly notebookId?: NotebookId;\n    readonly notebookName?: string;\n    readonly title: string;\n    readonly body: string;\n    readonly tags?: readonly string[];\n    readonly images?: readonly ImageUploadInput[];\n}"
          },
          {
            "name": "DeleteNotebookInput",
            "declaration": "export interface DeleteNotebookInput extends NotebookIdInput {\n    readonly expectedRevision: number;\n}"
          },
          {
            "name": "ImageData",
            "declaration": "export interface ImageData {\n    readonly image: NoteImage;\n    readonly data: string;\n}"
          },
          {
            "name": "ImageDataInput",
            "declaration": "export interface ImageDataInput {\n    readonly id: NoteImageId;\n}"
          },
          {
            "name": "ImageUploadInput",
            "declaration": "export interface ImageUploadInput {\n    readonly name: string;\n    readonly mediaType: NotebookImageMediaType;\n    readonly data: string;\n}"
          },
          {
            "name": "MutationResult",
            "declaration": "export interface MutationResult {\n    readonly ok: true;\n}"
          },
          {
            "name": "Note",
            "declaration": "export interface Note extends NoteSummary {\n    readonly body: string;\n    readonly images: NoteImage[];\n}"
          },
          {
            "name": "Notebook",
            "declaration": "export interface Notebook {\n    readonly id: NotebookId;\n    readonly name: string;\n    readonly revision: number;\n    readonly noteCount: number;\n    readonly archivedNoteCount: number;\n    readonly createdAt: string;\n    readonly updatedAt: string;\n}"
          },
          {
            "name": "NotebookId",
            "declaration": "export type NotebookId = Branded<'NotebookId'>;"
          },
          {
            "name": "NotebookIdInput",
            "declaration": "export interface NotebookIdInput {\n    readonly id: NotebookId;\n}"
          },
          {
            "name": "NotebookImageMediaType",
            "declaration": "export type NotebookImageMediaType = (typeof IMAGE_MEDIA_TYPES)[number];"
          },
          {
            "name": "NotebookOverview",
            "declaration": "export interface NotebookOverview {\n    readonly notebooks: Notebook[];\n    readonly tags: string[];\n    readonly activeNotes: number;\n    readonly archivedNotes: number;\n}"
          },
          {
            "name": "NotebookStore",
            "declaration": "export class NotebookStore {\n    overview(): NotebookOverview;\n    createNotebook(nameInput: string): Notebook;\n    search(input: NoteSearchInput): NoteSearchResult;\n    read(input: NoteIdInput): Note;\n    create(input: CreateNoteInput): Promise<Note>;\n    update(input: UpdateNoteInput): Promise<Note>;\n    archive(input: NoteLifecycleInput): Note;\n    restore(input: NoteLifecycleInput): Note;\n    revisions(input: NoteRevisionInput): NoteRevisionResult;\n    restoreRevision(input: RestoreRevisionInput): Note;\n    renameNotebook(input: RenameNotebookInput): Notebook;\n    deleteNotebook(input: DeleteNotebookInput): MutationResult;\n    deleteNote(input: NoteLifecycleInput): MutationResult;\n    addImage(input: NoteImageInput): Promise<Note>;\n    imageData(input: { id: NoteImageId; }): ImageData;\n    close(): void;\n}"
          },
          {
            "name": "NoteId",
            "declaration": "export type NoteId = Branded<'NoteId'>;"
          },
          {
            "name": "NoteIdInput",
            "declaration": "export interface NoteIdInput {\n    readonly id: NoteId;\n}"
          },
          {
            "name": "NoteImage",
            "declaration": "export interface NoteImage {\n    readonly id: NoteImageId;\n    readonly noteId: NoteId;\n    readonly name: string;\n    readonly mediaType: NotebookImageMediaType;\n    readonly bytes: number;\n    readonly width: number;\n    readonly height: number;\n    readonly digest: string;\n    readonly position: number;\n    readonly createdAt: string;\n}"
          },
          {
            "name": "NoteImageId",
            "declaration": "export type NoteImageId = Branded<'NoteImageId'>;"
          },
          {
            "name": "NoteImageInput",
            "declaration": "export interface NoteImageInput {\n    readonly noteId: NoteId;\n    readonly expectedRevision: number;\n    readonly image: ImageUploadInput;\n}"
          },
          {
            "name": "NoteLifecycleInput",
            "declaration": "export interface NoteLifecycleInput extends NoteIdInput {\n    readonly expectedRevision: number;\n}"
          },
          {
            "name": "NoteRevision",
            "declaration": "export interface NoteRevision {\n    readonly id: NoteRevisionId;\n    readonly noteId: NoteId;\n    readonly revision: number;\n    readonly notebookId: NotebookId;\n    readonly notebookName: string;\n    readonly title: string;\n    readonly body: string;\n    readonly tags: string[];\n    readonly images: NoteImage[];\n    readonly archivedAt: string | null;\n    readonly createdAt: string;\n}"
          },
          {
            "name": "NoteRevisionId",
            "declaration": "export type NoteRevisionId = Branded<'NoteRevisionId'>;"
          },
          {
            "name": "NoteRevisionInput",
            "declaration": "export interface NoteRevisionInput extends NoteIdInput {\n    readonly limit?: number;\n    readonly offset?: number;\n}"
          },
          {
            "name": "NoteRevisionResult",
            "declaration": "export interface NoteRevisionResult {\n    readonly revisions: NoteRevision[];\n    readonly total: number;\n    readonly hasMore: boolean;\n}"
          },
          {
            "name": "NoteSearchInput",
            "declaration": "export interface NoteSearchInput {\n    readonly query?: string;\n    readonly notebookId?: NotebookId;\n    readonly tags?: readonly string[];\n    readonly archived?: boolean;\n    readonly limit?: number;\n    readonly offset?: number;\n}"
          },
          {
            "name": "NoteSearchResult",
            "declaration": "export interface NoteSearchResult {\n    readonly notes: NoteSummary[];\n    readonly total: number;\n    readonly hasMore: boolean;\n}"
          },
          {
            "name": "NoteSummary",
            "declaration": "export interface NoteSummary {\n    readonly id: NoteId;\n    readonly notebookId: NotebookId;\n    readonly notebookName: string;\n    readonly title: string;\n    readonly excerpt: string;\n    readonly tags: string[];\n    readonly imageCount: number;\n    readonly revision: number;\n    readonly createdAt: string;\n    readonly updatedAt: string;\n    readonly archivedAt: string | null;\n}"
          },
          {
            "name": "RenameNotebookInput",
            "declaration": "export interface RenameNotebookInput extends NotebookIdInput {\n    readonly expectedRevision: number;\n    readonly name: string;\n}"
          },
          {
            "name": "RestoreRevisionInput",
            "declaration": "export interface RestoreRevisionInput {\n    readonly id: NoteId;\n    readonly revision: number;\n    readonly expectedRevision: number;\n}"
          },
          {
            "name": "UpdateNoteInput",
            "declaration": "export interface UpdateNoteInput {\n    readonly id: NoteId;\n    readonly expectedRevision: number;\n    readonly mode: 'append' | 'replace';\n    readonly title?: string;\n    readonly body?: string;\n    readonly notebookId?: NotebookId;\n    readonly notebookName?: string;\n    readonly tags?: readonly string[];\n    readonly images?: readonly ImageUploadInput[];\n    readonly removeImageIds?: readonly NoteImageId[];\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
